config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :events
  resources :event_attendees, only: %i[create destroy]
  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicAuth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/03774beff9.js" crossorigin="anonymous"></script>
    </head>

  <body>
    <div class="container">
    <div class="head my-3">
      <nav class="navbar navbar-expand-lg navbar-light head_custom-nav">
        <div class="navbar-header">
          <%= link_to "Private Events", root_path, class: "mx-2 text-primary" %>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
          <span><i class="fas fa-bars"></i></span> 
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <% if logged_in? %>
            <ul class="nav navbar-right ">
              <li><%= link_to 'All Events', events_path , class:"navbar-item mr-2" %></li>
              <li><%= link_to 'Create Event', new_event_path, class:"navbar-item mr-2" %></li>
              <li><%= link_to current_user.username, user_path(User.find(session[:user_id])), class:"navbar-item" %></li>
              <li><%= link_to "Log out", logout_path, class: "mx-2", method: :delete %></li> 
            </ul>
          <% else %>
            <ul class= "nav navbar-right">
            <li><%#= link_to 'All Events', events_path , class:"navbar-item mr-2" #%></li>
            <li><%= link_to "Log in", login_path, class: "mx-2" %></li> 
            <li><%= link_to "Sign up", signup_path, class: "mx-2" %></li>
            </ul>
          <% end %>      
         </div>
      </nav>
    </div>
    </div>
    <%= yield %>
  </body>
</html>